(diagram
 (eval (defun f-node (id desc) (file-node id ".TST" desc)))
 (eval (defun bold (string) (tt::with-style  (:font-size 8 :h-align :center :font "Helvetica-Bold") string)))
 (eval (defun stix (string) (tt::with-style (:font "STIXGeneral-Regular") string)))
 (eval (defun noto (string) (tt::with-style (:font "NotoMono") string)))
 (eval (defun pbook (string) (tt::with-style (:font "PadaukBook-Bold")  string)))
 (node b "j box")
 (node h "h-mode-mixin j")
 (node c (bold "cast j"))
 (node d (tt::paragraph (:font "Helvetica") (tt::with-style  (:font-size 8 :h-align :center :font "Helvetica-Bold") "j HEAD") :eol "And j more" :eol (bold "j Next line")))
 (file-node f ".csv" "A nice j file")
 (node g (tt::paragraph () (pbook "And a j test") :eol (pbook "Another j") :eol (pbook "Last-j")))
; (same-rank f g h)
; (same-rank b c)
 (cluster b h c)
 (-o b h)
 (<- b h)
 (<- b f)
 (-- b c)
 (<-> b c))

