(diagram
 (eval (defun f-node (id desc) (file-node id ".TST" desc)))
 (eval (defun bold (string) (tt::with-style  (:font-size 8 :h-align :center :font "Helvetica-Bold") string)))
 (node b "box")
 (node h "h-mode-mixin")
 (node c (bold "cast"))
 (node d (tt::paragraph () (tt::with-style  (:font-size 8 :h-align :center :font "Helvetica-Bold") "HEAD") :eol "And more" :eol (bold "Next line")))
 (file-node f ".csv" "A nice file")
 (f-node g "And a test")
; (same-rank f g h)
; (same-rank b c)
 (cluster b h c)
 (-o b h)
 (<- b h)
 (<- b f)
 (-- b c)
 (<-> b c))

